modLoader="javafml"
loaderVersion="[24,]"
issueTrackerURL="https://github.com/neoforged/FoxLauncher/issues"
license="LGPL v2.1"

[[mods]]
modId="foxlauncher"
# We use the global forge version
version="${global.forgeVersion}"
updateJSONURL="https://maven.neoforged.net/releases/net/neoforged/foxlauncher/promotions_slim.json"
displayName="FoxLauncher"
credits="Anyone who has contributed on Github and supports our development"
authors="The NeoForged Team"
description='''
    The FoxLauncher
    '''
